dist: trusty
sudo: required
language: node_js
node_js:
  - '8.10.0'
  - '6.2.2'
  - '5.7.0'
  - '4.8.0'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS mysqldump_test;'
install: yarn
script:
  - yarn build
  - yarn setup-travis
  - yarn test
  - yarn test-prod
